name: Update YouTube Videos

on:
  schedule:
    - cron: "0 * * * *" # every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Pull latest YouTube videos
        uses: DenverCoder1/github-readme-youtube@main
        with:
          channel_id: UCxXg6WaNmjgmXJF57jwQrvQ
          max_results: 1
          readme_path: README.md
          youtube_api_key: ${{ secrets.YOUTUBE_API_KEY }}

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Updated YouTube videos"
          git push
